# Generated by Django 5.2.9 on 2026-02-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0003_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='favoriteitem',
            old_name='added_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
